baseurl = "/"
languageCode = "zh-CN"
title = "Blurred code"
theme = ["hugo-notice","hugo-classic"]
googleAnalytics = "UA-71864552-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage =  true
enableRobotsTXT =  false
enableGitInfo = true
pygmentsCodeFences = false
# uglyurls = true
paginate= 40

[permalinks]
    post = "/:year/:month/:slug/" 
    # post = "/post/:slug/"

#  [[menu.main]]
#     name = "Home"
#     url = "/"
#     weight = 1

[[menu.main]]
    name = "misc"
    url = "/misc/"
    weight = 1

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 3
[[menu.main]]
    name = "About me"
    url = "/about/"
    weight = 4

[params]
    description = "A simple, minimal blog for those who love text."
    footer = "自豪的采用 [Hugo](https://gohugo.io/) | [hugo-classic](https://github.com/goodroot/hugo-classic) | panda[at]blurredcode.com"
    custom_css = ["css/theme-override.css"]
[markup]
  [markup.tableOfContents]
      endLevel = 3
      startLevel = 1
  [markup.goldmark.renderer]
      unsafe= true
[frontmatter]
lastmod = ["lastmod","updated",":git",":fileModTime",":default"]
date = ["date",":default"]

[params.utter]
enable = true
repo = "BlurryLight/BlurryLight_blog"
issueTerm = "title"
theme = "github-light"

[params.CDN]
enable = false
Host = "https://cdn.jsdelivr.net/gh/blurrylight/blurrylight_blog@pages-src/static/"
