baseurl = "/"
languageCode = "zh-CN"
title = "Blurred code"
theme = ["hugo-notice","hugo-classic"]
googleAnalytics = "UA-71864552-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage =  true
enableRobotsTXT =  false
enableGitInfo = true
pygmentsCodeFences = false
# uglyurls = true
paginate= 40

[permalinks]
    post = "/:year/:month/:slug/" 

#  [[menu.main]]
#     name = "Home"
#     url = "/"
#     weight = 1

[[menu.main]]
    name = "misc"
    url = "/misc/"
    weight = 1

[[menu.main]]
    name = "notes"
    url = "/notes/"
    weight = 2

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 4
[[menu.main]]
    name = "About me"
    url = "/about/"
    weight = 5

[params]
    description = "A simple, minimal blog for those who love text."
    footer = "自豪采用 [Hugo](https://gohugo.io/) | [hugo-classic](https://github.com/goodroot/hugo-classic) | [RSS Feed](/index.xml) | panda[at]blurredcode.com"
    custom_css = ["css/theme-override.css"]
[markup]
  [markup.tableOfContents]
      endLevel = 3
      startLevel = 1
  [markup.goldmark.renderer]
      unsafe= true
[frontmatter]
# lastmod = ["lastmod","updated",":git",":fileModTime",":default"]
# lastmod = [":git",":fileModTime",":default"]
# date = ["date",":default"]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[params.utter]
enable = true
repo = "BlurryLight/BlurryLight_blog"
issueTerm = "title"
theme = "github-light"

[params.GitRepo]
# this is for "Updated: time" with an hyperlink to commit hash, see single.html
enable = true
Host = "https://github.com/BlurryLight/BlurryLight_blog/commit/"

[params.Url]
    domain = "https://www.blurredcode.com"