name: github pages

on:
  push:
    branches:
      - pages-src
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false
env:
  OSS_ENDPOINT: ${{secrets.OSS_ENDPOINT}}
  OSS_KEY_ID: ${{secrets.OSS_KEY_ID}}
  OSS_KEY_SECRET: ${{secrets.OSS_KEY_SECRET}}
  OSS_BUCKET_NAME: ${{secrets.OSS_BUCKET_NAME}}
  HUGO_PARAMS_CDN_enable: false
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.68.3'
          # extended: true

      - name: Build
        run: hugo --minify
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

      # - name: Deploy OSS
      #   run: |
      #     chmod +x ./deploy_oss.sh
      #     ./deploy_oss.sh
      - name: set git config
        run: |
          git config core.quotePath false

      - name: Deploy github
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
          
      - name: update search engines
        run: |
          curl http://www.google.com/webmasters/sitemaps/ping?sitemap=https://www.blurredcode.com/sitemap.xml
          curl http://www.bing.com/webmaster/ping.aspx?siteMap=https://www.blurredcode.com/sitemap.xml

